# Generated by Django 4.0.4 on 2022-04-29 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='reja',
            field=models.TextField(blank=True),
        ),
    ]
