# Generated by Django 4.0.4 on 2022-04-29 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_alter_project_reja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='sana',
            field=models.DateField(),
        ),
    ]
